services:
  app:
    container_name: app
    build: .
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
