services:
  app:
    container_name: app
    command: python3 -u /code/app.py
    build: .
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
