name: icta-app

services:
  icta-app-api:
    build:
      context: .
      dockerfile: Dockerfile.health
    restart: on-failure
    tty: true
    ports:
      - "80:8000"
    networks:
      - icta-app-net
    environment:
      REDIS_HOST: icta-app-redis
      REDIS_PORT: 6379
      SIMULATE_ERROR: "true"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
  icta-app-redis:
    image: "redis:7.2.4-alpine"
    command: redis-server --save 20 1 --loglevel warning
    restart: on-failure
    networks:
      - icta-app-net
    volumes:
      - "icta-app-redis-data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  icta-app-net:

volumes:
  icta-app-redis-data:
