name: icta-app

services:
  icta-app-api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000 --reload-dir /usr/src/app/
    ports:
      - "80:8000"
    networks:
      - icta-app-net
    volumes:
      - .:/usr/src/app/
    environment:
      REDIS_HOST: icta-app-redis
      REDIS_PORT: 6379
  icta-app-redis:
    image: "redis:7.2.4-alpine"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - icta-app-net
    volumes:
      - "icta-app-redis-data:/data"

networks:
  icta-app-net:

volumes:
  icta-app-redis-data:
